language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
# environment variables to set
#env: RELO_PATH=/path/to/relo
# command to run tests
script: nosetests
# command to install dependencies
install: 
  - pip install -r requirements.txt --use-mirrors
