#!/usr/bin/env python
#encoding: utf-8

import relo
from relo.core import config

__author__ = "cwoebker"
__version__ = config.get_version()
__copyright__ = "cwoebker"
__license__ = "See in LICENSE file"

if __name__ == '__main__':
    relo.main()